In [2]:
import numpy as np, pandas as pd;

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [8]:
movies['id'][0]

19995

In [5]:
movies.shape

(4803, 20)

In [5]:
credits.head(1)['crew'].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "depart

In [6]:
movies = movies.merge(credits, on='title')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

tags = genre, id, keywords, title, overview, cast, crew,

original_language, production_companies, 

release_date, revenue, vote_average, vote_count,

In [8]:
movies = movies[['movie_id','title','overview','original_language','production_companies','genres','keywords','cast','crew']]

In [9]:
movies.head()

,movie_id,title,overview,original_language,production_companies,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",en,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",en,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,en,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,en,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...",en,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.isnull().sum()

movie_id                0
title                   0
overview                0
original_language       0
production_companies    0
genres                  0
keywords                0
cast                    0
crew                    0
dtype: int64

In [12]:
movies.duplicated().sum()

0

changing columns into suitable keywords.

In [13]:
import ast

In [14]:
def change(tag):
    final_list = []
    for i in ast.literal_eval(tag):
        final_list.append(i['name'])
        
    return final_list;

In [15]:
movies['genres'] = movies['genres'].apply(change)

In [16]:
movies['keywords'] = movies['keywords'].apply(change)

In [17]:
#taking only 4 lead actor/actress names

def change_cast(tag):
    final_list = []
    flag = 0
    for i in ast.literal_eval(tag):
        if flag < 4:
            final_list.append(i['name'])
            flag +=1
        else:
            break
    return final_list;

In [18]:
movies['cast'] = movies['cast'].apply(change_cast)

In [19]:
#taking names of all Directors

def change_crew(tag):
    final_list = []
    for i in ast.literal_eval(tag):
        if i['job'] == 'Director':
            final_list.append(i['name'])
         
    return final_list;

In [20]:
movies['crew'] = movies['crew'].apply(change_crew)

In [21]:
#taking names of all production_companies

def change_prod_comp(tag):
    final_list = []
    for i in ast.literal_eval(tag):
        final_list.append(i['name'])
         
    return final_list;

In [22]:
movies['production_companies'] = movies['production_companies'].apply(change_prod_comp)

In [23]:
movies['overview'] = movies['overview'].apply(lambda a:a.split())

In [24]:
# joining names by removing spaces
def remove_space(names):
    final_list = []
    for i in names:
        final_list.append(i.replace(" ",""))
    return final_list

In [25]:
movies['crew'] = movies['crew'].apply(remove_space)
movies['cast'] = movies['cast'].apply(remove_space)
movies['production_companies'] = movies['production_companies'].apply(remove_space)
# note that storing "sciencefiction" will be better then "science fiction" so-

movies['keywords'] = movies['keywords'].apply(remove_space)
movies['genres'] = movies['genres'].apply(remove_space)

In [26]:
movies['original_language'] = movies['original_language'].apply(lambda a:a.split())

In [27]:
movies.head()

,movie_id,title,overview,original_language,production_companies,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",[en],"[IngeniousFilmPartners, TwentiethCenturyFoxFil...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",[en],"[WaltDisneyPictures, JerryBruckheimerFilms, Se...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",[en],"[ColumbiaPictures, Danjaq, B24]","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",[en],"[LegendaryPictures, WarnerBros., DCEntertainme...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",[en],[WaltDisneyPictures],"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [28]:
movies['tags'] = movies['overview'] + movies['keywords'] + movies['genres'] + movies['cast'] + movies['crew'] + movies['production_companies'] + movies['original_language']

In [29]:
dataframe = movies[['movie_id', 'title', 'tags']]

In [30]:
dataframe['tags'] = dataframe['tags'].apply(lambda a:" ".join(a))

C:\Users\punit\AppData\Local\Temp/ipykernel_9368/4178702363.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['tags'] = dataframe['tags'].apply(lambda a:" ".join(a))

In [31]:
dataframe['tags'] = dataframe['tags'].apply(lambda a:a.lower())

C:\Users\punit\AppData\Local\Temp/ipykernel_9368/1267211395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['tags'] = dataframe['tags'].apply(lambda a:a.lower())

In [81]:
dataframe.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

# creating a data set for collaborative filtering(cf)

In [114]:
sorted_id = sorted(dataframe['movie_id'])

In [137]:
sorted_id
# 4806

[5,
 11,
 12,
 13,
 14,
 16,
 18,
 19,
 20,
 22,
 24,
 25,
 28,
 33,
 35,
 38,
 55,
 58,
 59,
 62,
 65,
 66,
 68,
 69,
 70,
 71,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 83,
 85,
 87,
 89,
 90,
 95,
 96,
 98,
 100,
 103,
 104,
 105,
 106,
 107,
 111,
 114,
 115,
 116,
 117,
 118,
 120,
 121,
 122,
 128,
 129,
 134,
 137,
 141,
 142,
 146,
 149,
 152,
 153,
 154,
 155,
 157,
 161,
 162,
 163,
 165,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 179,
 180,
 182,
 184,
 186,
 187,
 189,
 193,
 194,
 196,
 197,
 199,
 200,
 201,
 203,
 205,
 207,
 214,
 215,
 217,
 218,
 219,
 223,
 226,
 227,
 231,
 235,
 238,
 239,
 240,
 242,
 243,
 245,
 248,
 251,
 252,
 253,
 254,
 257,
 261,
 268,
 268,
 272,
 274,
 277,
 278,
 279,
 280,
 284,
 285,
 288,
 289,
 291,
 292,
 296,
 297,
 298,
 302,
 306,
 309,
 310,
 311,
 314,
 319,
 320,
 321,
 322,
 326,
 327,
 329,
 330,
 331,
 332,
 334,
 335,
 338,
 342,
 345,
 346,
 348,
 350,
 364,
 377,
 380,
 387,
 388,
 389,
 391,
 392,
 393,
 395,
 398,
 400,
 401,
 403,
 404,
 408,
 409,
 411,
 414,
 415,
 421,
 423,
 424,
 425,
 429,
 431,
 433,
 435,
 436,
 440,
 451,
 453,
 454,
 455,
 462,
 464,
 468,
 470,
 473,
 479,
 480,
 489,
 492,
 496,
 497,
 500,
 503,
 504,
 507,
 508,
 509,
 510,
 512,
 522,
 524,
 525,
 526,
 533,
 534,
 535,
 539,
 540,
 542,
 544,
 546,
 547,
 549,
 550,
 557,
 558,
 559,
 562,
 563,
 568,
 573,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 584,
 585,
 586,
 587,
 588,
 590,
 591,
 592,
 593,
 594,
 595,
 597,
 598,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 612,
 613,
 615,
 616,
 617,
 619,
 621,
 622,
 627,
 628,
 629,
 630,
 634,
 639,
 640,
 641,
 642,
 644,
 646,
 650,
 652,
 654,
 657,
 658,
 660,
 663,
 664,
 666,
 667,
 668,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 679,
 680,
 681,
 682,
 686,
 687,
 688,
 691,
 692,
 693,
 694,
 698,
 699,
 700,
 702,
 703,
 704,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 744,
 745,
 746,
 747,
 752,
 754,
 755,
 756,
 762,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 782,
 783,
 786,
 787,
 788,
 790,
 792,
 794,
 795,
 796,
 801,
 802,
 805,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 816,
 817,
 818,
 819,
 820,
 821,
 824,
 826,
 834,
 837,
 838,
 840,
 841,
 844,
 846,
 848,
 849,
 850,
 853,
 854,
 855,
 857,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 868,
 869,
 872,
 873,
 874,
 879,
 881,
 887,
 888,
 889,
 905,
 907,
 913,
 920,
 921,
 924,
 925,
 926,
 927,
 928,
 935,
 943,
 944,
 947,
 948,
 950,
 951,
 953,
 954,
 955,
 956,
 957,
 978,
 979,
 985,
 987,
 990,
 1018,
 1024,
 1051,
 1073,
 1088,
 1090,
 1091,
 1103,
 1116,
 1123,
 1124,
 1125,
 1164,
 1165,
 1213,
 1245,
 1246,
 1248,
 1250,
 1251,
 1255,
 1255,
 1257,
 1259,
 1262,
 1265,
 1266,
 1268,
 1271,
 1272,
 1273,
 1282,
 1359,
 1360,
 1365,
 1366,
 1368,
 1369,
 1370,
 1372,
 1378,
 1381,
 1382,
 1389,
 1391,
 1402,
 1408,
 1412,
 1415,
 1417,
 1422,
 1424,
 1427,
 1428,
 1429,
 1430,
 1435,
 1439,
 1440,
 1443,
 1452,
 1487,
 1491,
 1493,
 1494,
 1495,
 1497,
 1499,
 1523,
 1535,
 1537,
 1538,
 1542,
 1544,
 1546,
 1547,
 1548,
 1550,
 1551,
 1555,
 1562,
 1571,
 1572,
 1573,
 1574,
 1576,
 1577,
 1578,
 1579,
 1581,
 1584,
 1585,
 1586,
 1587,
 1588,
 1590,
 1591,
 1593,
 1597,
 1598,
 1599,
 1613,
 1619,
 1620,
 1621,
 1624,
 1635,
 1636,
 1637,
 1639,
 1640,
 1642,
 1645,
 1646,
 1648,
 1649,
 1651,
 1656,
 1667,
 1669,
 1677,
 1683,
 1685,
 1687,
 1688,
 1690,
 1691,
 1696,
 1698,
 1701,
 1705,
 1710,
 1717,
 1722,
 1724,
 1725,
 1726,
 1729,
 1734,
 1735,
 1770,
 1771,
 1777,
 1779,
 1781,
 1788,
 1792,
 1808,
 1809,
 1813,
 1817,
 1819,
 1824,
 1830,
 1831,
 1832,
 1833,
 1844,
 1850,
 1852,
 1858,
 1865,
 1874,
 1878,
 1880,
 1883,
 1885,
 1887,
 1891,
 1892,
 1893,
 1894,
 1895,
 1900,
 1901,
 1903,
 1904,
 1907,
 1909,
 1911,
 1913,
 1921,
 1924,
 1927,
 1930,
 1931,
 1933,
 1934,
 1946,
 1947,
 1948,
 1949,
 1950,
 1951,
 1954,
 1955,
 1956,
 1957,
 1958,
 1961,
 1966,
 1969,
 1970,
 1975,
 1979,
 1985,
 1988,
 1989,
 1995,
 1996,
 1997,
 1999,
 2001,
 2008,
 2009,
 2011,
 2013,
 2018,
 2022,
 2023,
 2024,
 2026,
 2034,
 2043,
 2044,
 2048,
 2054,
 2055,
 2056,
 2057,
 2059,
 2062,
 2067,
 2069,
 2074,
 2080,
 2084,
 2085,
 2088,
 2100,
 2105,
 2110,
 2112,
 2114,
 2116,
 2118,
 2119,
 2122,
 2123,
 2133,
 2135,
 2140,
 2142,
 2148,
 2155,
 2157,
 2162,
 2163,
 2176,
 2185,
 2196,
 2207,
 2211,
 2251,
 2252,
 2253,
 2255,
 2266,
 2268,
 2270,
 2275,
 2277,
 2280,
 2287,
 2288,
 2289,
 2290,
 2292,
 2293,
 2294,
 2295,
 2300,
 2309,
 2310,
 2312,
 2320,
 2355,
 2359,
 2370,
 2395,
 2428,
 2447,
 2453,
 2454,
 2486,
 2493,
 2501,
 2502,
 2503,
 2539,
 2567,
 2575,
 2577,
 2604,
 2610,
 2619,
 2621,
 2636,
 2637,
 2639,
 2642,
 2649,
 2652,
 2655,
 2661,
 2661,
 2662,
 2666,
 2667,
 2669,
 2675,
 2687,
 2698,
 2749,
 2752,
 2755,
 2756,
 2757,
 2770,
 2771,
 2779,
 2786,
 2787,
 2789,
 2830,
 2832,
 2841,
 2895,
 2898,
 2900,
 2907,
 2925,
 2959,
 2976,
 2977,
 2989,
 3021,
 3028,
 3033,
 3034,
 3040,
 3049,
 3050,
 3059,
 3060,
 3062,
 3078,
 3080,
 3082,
 3083,
 3089,
 3093,
 3116,
 3131,
 3132,
 3170,
 3172,
 3175,
 3179,
 3291,
 3472,
 3482,
 3489,
 3509,
 3512,
 3536,
 3558,
 3580,
 3587,
 3594,
 3595,
 3597,
 3600,
 3604,
 3635,
 3638,
 3682,
 3683,
 3766,
 3877,
 3902,
 3933,
 3981,
 3989,
 4011,
 4012,
 4032,
 4105,
 4107,
 4108,
 4133,
 4147,
 4148,
 4170,
 4174,
 4232,
 4233,
 4234,
 4244,
 4248,
 4251,
 4256,
 4257,
 4258,
 4327,
 4347,
 4348,
 4349,
 4379,
 4380,
 4421,
 4442,
 4464,
 4474,
 4476,
 4477,
 4512,
 4513,
 4515,
 4517,
 4518,
 4523,
 4547,
 4550,
 4551,
 4553,
 4566,
 4584,
 4597,
 4599,
 4614,
 4638,
 4657,
 4688,
 4723,
 4806,
 4816,
 4824,
 4836,
 4858,
 4911,
 4912,
 4922,
 4929,
 4935,
 4942,
 4944,
 4951,
 4953,
 4958,
 4959,
 4960,
 4964,
 4965,
 4967,
 4970,
 4982,
 4995,
 4997,
 5038,
 5072,
 5123,
 5125,
 5126,
 5137,
 5172,
 5174,
 5175,
 5176,
 5178,
 5236,
 5255,
 5279,
 5353,
 5393,
 5491,
 5494,
 5503,
 5516,
 5528,
 5550,
 5551,
 5559,
 5689,
 5708,
 5722,
 5723,
 5759,
 5769,
 5780,
 5820,
 5822,
 5852,
 5854,
 5876,
 5900,
 5902,
 5915,
 5925,
 5955,
 5966,
 5971,
 5994,
 6007,
 6016,
 6020,
 6023,
 6038,
 6068,
 6071,
 6073,
 6106,
 6114,
 6116,
 6171,
 6217,
 6278,
 6282,
 6415,
 6435,
 6439,
 6440,
 6466,
 6477,
 6478,
 6479,
 6488,
 6519,
 6520,
 6521,
 6537,
 6538,
 6552,
 6557,
 6575,
 6615,
 6623,
 6639,
 6687,
 6795,
 6877,
 6933,
 6947,
 6950,
 6957,
 6961,
 6963,
 6964,
 6968,
 6972,
 6973,
 6977,
 6978,
 7006,
 ...]

In [218]:
links_cf = pd.read_csv('links.csv')
ratings_cf = pd.read_csv('ratings.csv')
movies_cf = pd.read_csv('movies.csv')

In [219]:
ratings_cf = ratings_cf.merge(links_cf, on='movieId')

In [220]:
ratings_cf

        userId  movieId  rating   timestamp   imdbId    tmdbId
0            1        1     4.0   964982703   114709     862.0
1            5        1     4.0   847434962   114709     862.0
2            7        1     4.5  1106635946   114709     862.0
3           15        1     2.5  1510577970   114709     862.0
4           17        1     4.5  1305696483   114709     862.0
...        ...      ...     ...         ...      ...       ...
100831     610   160341     2.5  1479545749   118745   30948.0
100832     610   160527     4.5  1479544998    66806   90351.0
100833     610   160836     3.0  1493844794   798722   70193.0
100834     610   163937     3.5  1493848789  1540011  351211.0
100835     610   163981     3.5  1493850155  3835080  284564.0

[100836 rows x 6 columns]

In [221]:
ratings_cf.rename(columns = {'tmdbId':'movie_id'}, inplace = True)
ratings_cf.rename(columns = {'userId':'userid'}, inplace = True)

In [222]:
ratings_cf

        userid  movieId  rating   timestamp   imdbId  movie_id
0            1        1     4.0   964982703   114709     862.0
1            5        1     4.0   847434962   114709     862.0
2            7        1     4.5  1106635946   114709     862.0
3           15        1     2.5  1510577970   114709     862.0
4           17        1     4.5  1305696483   114709     862.0
...        ...      ...     ...         ...      ...       ...
100831     610   160341     2.5  1479545749   118745   30948.0
100832     610   160527     4.5  1479544998    66806   90351.0
100833     610   160836     3.0  1493844794   798722   70193.0
100834     610   163937     3.5  1493848789  1540011  351211.0
100835     610   163981     3.5  1493850155  3835080  284564.0

[100836 rows x 6 columns]

In [223]:
data_cf = dataframe.merge(ratings_cf, on='movie_id').drop(['movieId', 'imdbId', 'timestamp'],axis=1)
data_cf

,movie_id,title,tags,userid,rating
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",10,2.5
1,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",15,3.0
2,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",18,4.0
3,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",21,4.0
4,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",22,3.5
...,...,...,...,...,...
70394,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,493,4.0
70395,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,580,4.0
70396,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,599,2.0
70397,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,606,3.5
70398,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,608,3.0

In [224]:
# removing movies having less than 2 user ratings,
# and users who rated less than 5 movies
# cold start problem will be taken care by content based
min_movie_ratings = 2 #a movie has was rated at least 
min_user_ratings =  5 #a user rated movies at least

data_cf = data_cf.groupby("movie_id").filter(lambda x: x['movie_id'].count() >= min_movie_ratings)
data_cf = data_cf.groupby("userid").filter(lambda x: x['userid'].count() >= min_user_ratings)

In [225]:
data_cf

,movie_id,title,tags,userid,rating
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",10,2.5
1,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",15,3.0
2,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",18,4.0
3,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",21,4.0
4,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",22,3.5
...,...,...,...,...,...
70394,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,493,4.0
70395,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,580,4.0
70396,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,599,2.0
70397,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,606,3.5
70398,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,608,3.0

In [226]:
data_cf.isnull().sum()

movie_id    0
title       0
tags        0
userid      0
rating      0
dtype: int64

In [227]:
data_cf.shape

(69903, 5)

In [228]:
data_cf.drop_duplicates(inplace =True)

In [229]:
data_cf.duplicated().sum()

0

In [230]:
data_cf['title'][15535]

'Independence Day'

In [231]:
user_ratings = data_cf.pivot_table(index=['userid'], columns=['title'], values='rating')
user_ratings.head(10)

title,(500) Days of Summer,10 Cloverfield Lane,10 Things I Hate About You,102 Dalmatians,11:14,12 Angry Men,12 Rounds,12 Years a Slave,127 Hours,13 Going on 30,...,Zombieland,Zookeeper,Zoolander,Zoolander 2,[REC],[REC]²,eXistenZ,xXx,xXx: State of the Union,Æon Flux
userid,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [236]:
# filling NaN with 0.
user_ratings = user_ratings.fillna(0)
data_cf = data_cf.fillna(0)
#dropna(thresh=5, axis=1)

In [237]:
user_ratings

title,(500) Days of Summer,10 Cloverfield Lane,10 Things I Hate About You,102 Dalmatians,11:14,12 Angry Men,12 Rounds,12 Years a Slave,127 Hours,13 Going on 30,...,Zombieland,Zookeeper,Zoolander,Zoolander 2,[REC],[REC]²,eXistenZ,xXx,xXx: State of the Union,Æon Flux
userid,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,4.5,3.5,0.0,4.5
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,3.5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,3.5,0.0,4.0,0.0,4.0,3.5,0.0,2.0,1.5,0.0

In [238]:
data_cf

,movie_id,title,tags,userid,rating
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",10,2.5
1,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",15,3.0
2,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",18,4.0
3,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",21,4.0
4,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",22,3.5
...,...,...,...,...,...
70394,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,493,4.0
70395,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,580,4.0
70396,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,599,2.0
70397,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,606,3.5
70398,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,608,3.0

In [33]:
import nltk

In [34]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
### pictures, picture and other similiar will now became pictur
def remove_similar_words(data):
    final_list = []
    for i in data.split():
        final_list.append(ps.stem(i))
    
    return " ".join(final_list)

In [36]:
ps.stem('loving')

'love'

In [80]:
dataframe['tags'] = dataframe['tags'].apply(remove_similar_words)

C:\Users\punit\AppData\Local\Temp/ipykernel_9368/522528730.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['tags'] = dataframe['tags'].apply(remove_similar_words)

testing bag of words

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [39]:
vector = cv.fit_transform(dataframe['tags']).toarray()

In [40]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
cv.get_feature_names()

c:\users\punit\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '1492pictur',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1985',
 '1990',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2009',
 '20th',
 '21lapsentertain',
 '24',
 '25',
 '2929product',
 '30',
 '300',
 '3artsentertain',
 '3d',
 '40',
 '40acres',
 '50',
 '500',
 '60',
 '70',
 'a24',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'adam',
 'adambrodi',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanalda',
 'alanarkin',
 'alaska',
 'albert',
 'albertbrook',
 'alcatraz',
 'alcohol',
 'alconentertain',
 'alecbaldwin',
 'alex',
 'alexapenavega',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'alien',
 'alieninvas',
 'alienlife',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allianceatlantiscommun',
 'alliancefilm',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alphavillefilm',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'amblinentertain',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootbal',
 'americanfootballplay',
 'americanzoetrop',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amulefilmwork',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'andyserki',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'annapurnapictur',
 'annasophiarobb',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'announc',
 'annual',
 'anonym',
 'anonymouscont',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antihero',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'apatowproduct',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appianway',
 'appl',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artisanentertain',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asid',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atlasentertain',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'badhatharryproduct',
 'badrobot',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'bbc',
 'bbcfilm',
 'beach',
 'beaconcommun',
 'beaconpictur',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'benderspink',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berniemac',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'big',
 'bigger',
 'biggest',
 'bigscreenproduct',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blame',
 'blend',
 'blind',
 'blindingedgepictur',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'blueskystudio',
 'blumhouseproduct',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'boldfilm',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breath',
 'breckinmey',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briancox',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brien',
 'bright',
 'brightlightpictur',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishbroadcastingcorporation',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucedern',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'budget',
 'build',
 'building',
 'built',
 'bull',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'canadianfilmorvideoproductiontaxcredit',
 'canal',
 'canalplu',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'cannonfilm',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'car',
 'caraccid',
 'caravanpictur',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolcopictur',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'castlerockentertain',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinekeen',
 'catherineo',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'cbsfilm',
 'cedrictheentertain',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'central',
 'centrenationaldelacinématographie',
 'centropolisentertain',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channelfourfilm',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charless',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'cherninentertain',
 'chevychas',
 'cheyenneenterpris',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'children',
 'chill',
 'chimp',
 'china',
 'chinafilmco',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherguest',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'cinergipicturesentertain',
 'ciné',
 'cinécinéma',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'clown',
 'club',
 'clue',
 'clutch',
 'cn',
 'cnc',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colehaus',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'colorforc',
 'columbiapictur',
 'columbiapicturescorpor',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'condit',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connel',
 'connienielsen',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantinfilmprodukt',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'convers',
 'convict',
 'convinc',
 ...]

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [101]:
similarity = cosine_similarity(vector)

In [102]:
similarity

array([[1.        , 0.10529963, 0.1067521 , ..., 0.06726728, 0.0238705 ,
        0.0238705 ],
       [0.10529963, 1.        , 0.08219949, ..., 0.04604093, 0.02450715,
        0.04901431],
       [0.1067521 , 0.08219949, 1.        , ..., 0.046676  , 0.0248452 ,
        0.0248452 ],
       ...,
       [0.06726728, 0.04604093, 0.046676  , ..., 1.        , 0.06262243,
        0.06262243],
       [0.0238705 , 0.02450715, 0.0248452 , ..., 0.06262243, 1.        ,
        0.11111111],
       [0.0238705 , 0.04901431, 0.0248452 , ..., 0.06262243, 0.11111111,
        1.        ]])

In [123]:
def recommend_bow(movie):
    index = dataframe[dataframe['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:9]:
        print(dataframe.iloc[i[0]].title)
        #print(dataframe.iloc[i[0]].	movie_id)

In [124]:
recommend_bow('Harry Potter and the Philosopher\'s Stone')

Harry Potter and the Chamber of Secrets
1982
The Adventures of Elmo in Grouchland
Harry Potter and the Order of the Phoenix
The R.M.
Krrish
Flying By
Harry Potter and the Goblet of Fire

# bert (google 2018)
lets try text vectorization using bert

In [49]:
from sentence_transformers import SentenceTransformer
bert = SentenceTransformer('bert-base-nli-mean-tokens')

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [53]:
#Get Embeddings
sentence_embeddings = bert.encode(dataframe['tags'].tolist())

In [54]:
sentence_embeddings[0]

array([-4.91697550e-01,  6.89592063e-01,  3.93348299e-02,  1.38256833e-01,
        2.60770917e-01, -2.96357006e-01, -9.73715335e-02,  3.06578092e-02,
       -3.51981193e-01, -3.54719460e-01, -6.89107239e-01,  3.24435413e-01,
        8.37678090e-02,  1.25901496e+00, -3.87318403e-01,  7.05903411e-01,
       -5.63158870e-01, -1.10753529e-01, -2.72041023e-01,  5.48841208e-02,
       -6.69977784e-01,  3.03379238e-01, -2.21723080e-01,  1.22983716e-01,
        3.19108963e-01,  3.36315483e-01, -1.68864250e-01,  3.73172402e-01,
       -5.32829881e-01,  5.29235005e-01, -6.38261855e-01, -7.81004578e-02,
       -4.28529739e-01, -1.40193120e-01, -1.83872789e-01,  2.59372741e-01,
       -2.25954816e-01,  2.66759902e-01,  2.82817304e-01,  2.63409525e-01,
       -2.34934390e-01, -6.55764699e-01,  2.35988293e-02, -5.92735112e-01,
       -1.52146387e+00, -1.38971165e-01,  5.82128465e-01,  4.46476877e-01,
        3.09455007e-01, -4.54341441e-01,  9.74503458e-01,  3.09434116e-01,
        2.02572659e-01, -8.03052902e-01,  2.52524883e-01,  1.11018881e-01,
        5.53194702e-01, -8.23101401e-01, -4.66848850e-01,  4.48595941e-01,
       -5.06933510e-01,  2.93130040e-01, -1.48462325e-01, -8.88805538e-02,
       -3.19551319e-01, -4.17650864e-03,  9.59680825e-02, -2.59660363e-01,
       -9.31458950e-01, -6.70361757e-01,  6.49616420e-02, -5.26996851e-01,
       -8.35275710e-01,  1.34295598e-01,  2.32547492e-01, -6.81849957e-01,
        2.95108497e-01,  3.37090164e-01,  8.29608142e-01,  1.01385176e-01,
        4.58097637e-01, -2.19164774e-01,  3.71600598e-01, -2.04528198e-01,
        4.82238114e-01,  2.96730787e-01,  1.97926573e-02, -2.35999763e-01,
       -5.17731130e-01, -2.38915280e-01,  4.74580050e-01,  2.14745402e-01,
       -1.90141216e-01,  3.12830269e-01, -5.69799840e-01, -2.78880507e-01,
        3.26529801e-01, -3.45944554e-01, -5.93194187e-01,  1.04442549e+00,
       -5.04692554e-01,  4.85926867e-01, -3.07563365e-01,  3.35276872e-01,
       -1.84218496e-01, -4.16293979e-01,  2.01949820e-01, -6.52263463e-01,
       -1.27320302e+00,  6.15987122e-01,  6.16682827e-01,  7.36759007e-01,
       -1.82864383e-01,  3.31907719e-01, -6.99909270e-01, -5.07809937e-01,
        5.45663685e-02,  6.61388636e-01,  6.09801173e-01,  8.48063827e-01,
        1.04667139e+00,  1.67817511e-02,  8.12924951e-02,  1.48350015e-01,
        4.54218477e-01,  6.84367120e-01,  5.83765149e-01,  2.68015802e-01,
       -9.33121383e-01, -3.89512777e-02,  5.82365096e-01,  7.75581598e-01,
       -5.98851025e-01,  4.98553962e-01,  2.02229545e-01,  2.13379413e-01,
        2.24908680e-01, -9.55658734e-01, -2.28456646e-01, -5.30764580e-01,
       -5.53601384e-01, -5.24195671e-01, -6.53092042e-02, -5.82284451e-01,
        1.83546901e-01, -9.58739370e-02,  2.08453506e-01, -6.35425091e-01,
       -5.13616621e-01,  5.63771069e-01, -5.99079728e-01, -3.74645948e-01,
       -3.74501318e-01,  3.02662224e-01, -2.56759256e-01, -1.71282887e+00,
       -4.49082643e-01,  7.25869775e-01, -2.01919615e-01,  8.97946537e-01,
       -1.42117158e-01,  3.27052742e-01, -1.00498319e+00,  1.19889103e-01,
        9.28489864e-01, -9.12623763e-01,  3.95106584e-01, -3.25398445e-01,
       -4.93975043e-01, -4.73545104e-01, -5.86440384e-01,  4.24794018e-01,
        9.75294411e-01, -4.83098328e-01,  3.06025982e-01, -1.94058806e-01,
        1.00636315e+00,  3.41431618e-01,  1.61457621e-02, -1.15812622e-01,
       -4.14463818e-01, -2.06969187e-01, -8.29908788e-01,  2.71490306e-01,
       -4.55485165e-01, -1.90880552e-01, -1.06440820e-01, -4.38345075e-01,
        3.68376642e-01,  2.49456301e-01, -1.03425241e+00, -2.32147902e-01,
        2.68529356e-01, -1.37641057e-01, -2.55159467e-01,  2.87086904e-01,
       -2.49285996e-01,  1.19181120e+00,  3.06946505e-02,  5.98413229e-01,
       -4.63208705e-01,  1.29673809e-01,  1.48064747e-01, -1.69975489e-01,
        1.53049409e-01,  9.64401543e-01,  3.63283157e-01,  5.62006980e-02,
       -5.96820712e-01,  9.81734619e-02, -5.15422106e-01,  2.56960124e-01,
        4.09675956e-01, -2.51743853e-01,  5.97642124e-01, -5.45983575e-02,
       -5.65798521e-01, -1.50509253e-01,  3.65732521e-01,  2.10736439e-01,
        3.23923677e-01, -8.51617604e-02,  1.85464278e-01,  1.31223211e-03,
       -5.88914335e-01,  1.28281832e+00,  4.49058414e-01, -1.07155049e+00,
        5.43476157e-02,  9.33221936e-01,  1.32435247e-01, -6.83044195e-01,
       -6.85705304e-01, -6.91673458e-02,  1.67151779e-01,  1.48993567e-01,
       -7.08948612e-01, -1.85184121e-01,  3.66096258e-01, -1.20663412e-01,
       -7.81838819e-02,  7.57275403e-01,  8.51043016e-02,  1.20751166e+00,
       -2.71470934e-01, -2.06088543e-01,  9.47394520e-02, -3.73970456e-02,
       -4.56534505e-01,  6.03725433e-01, -1.41923833e+00, -1.25009879e-01,
        6.69050694e-01,  3.19697499e-01,  1.18543148e-01, -2.19887152e-01,
       -5.55729210e-01,  1.18698172e-01, -3.19466323e-01, -7.29093701e-02,
       -2.76915640e-01,  1.18193544e-01, -2.80260146e-01,  3.77214663e-02,
       -6.01895005e-02, -9.51562881e-01,  3.12477618e-01,  3.64280164e-01,
       -8.67870569e-01,  3.44806403e-01, -5.72873354e-01, -6.49667740e-01,
       -6.46852732e-01,  2.21549615e-01, -3.86008143e-01, -3.06933880e-01,
       -4.81552631e-01, -1.24664813e-01,  4.20289874e-01,  2.48462752e-01,
        2.02309579e-01,  3.29873592e-01, -6.02162004e-01,  1.99812666e-01,
       -4.17666167e-01,  1.23278165e+00,  5.86913049e-01, -6.36190653e-01,
       -5.93635857e-01,  4.11491454e-01,  2.82988194e-02, -4.83900756e-01,
       -5.94962537e-01,  7.10143447e-01,  5.90275265e-02, -1.64421022e-01,
        6.46920919e-01, -3.74934852e-01,  9.99835253e-01, -2.95749098e-01,
       -3.65065157e-01,  2.40575463e-01, -1.03859580e+00,  2.21035883e-01,
        1.88327178e-01, -4.30210084e-01,  4.34130132e-01,  1.26934156e-01,
       -1.96900141e+00, -7.20011353e-01, -8.44623983e-01, -2.05251038e-01,
        7.55437851e-01,  1.33555901e+00,  9.90165889e-01, -1.58976808e-01,
       -7.79724538e-01, -1.38679966e-01, -2.42121816e-02, -5.39879382e-01,
       -6.43298686e-01,  2.33692348e-01,  2.42385596e-01,  1.53346092e-01,
        7.26260602e-01, -6.76855445e-01, -6.32848978e-01,  5.05855642e-02,
       -2.41228938e-01, -2.37802356e-01,  2.34379441e-01, -9.19075608e-01,
        5.15213370e-01,  6.33212686e-01,  5.22062004e-01, -3.66410971e-01,
       -4.42021936e-02,  1.97336674e-01, -1.31506160e-01,  2.99704313e-01,
        5.32231927e-01, -6.93947554e-01, -9.77993757e-02,  8.39990914e-01,
       -2.78388679e-01, -7.82459378e-01,  6.26841187e-01,  1.06483305e+00,
       -8.23651999e-02, -4.44891639e-02,  9.78850201e-02, -3.93703282e-01,
        5.95401227e-01, -9.72815216e-01, -2.10256070e-01,  1.78940341e-01,
       -1.08858958e-01,  8.57954919e-01, -6.46384060e-01,  2.89969981e-01,
       -9.58346903e-01,  2.54626930e-01, -2.41092995e-01,  4.44898456e-01,
       -3.50210071e-01,  7.07066953e-01, -6.85366571e-01,  2.22223736e-02,
       -4.75547239e-02,  2.81211078e-01, -1.23944916e-01,  4.12401617e-01,
       -1.01408434e+00,  2.37654895e-01, -4.53395769e-02, -4.19610023e-01,
        1.73390314e-01, -8.99727225e-01, -5.19214272e-01, -1.70756549e-01,
       -4.58289772e-01, -5.88361800e-01,  6.95559800e-01,  2.45784074e-01,
       -9.92042482e-01, -5.83340645e-01, -3.25270176e-01,  2.18101129e-01,
       -4.38221127e-01,  7.85026476e-02,  1.50522128e-01,  1.99823812e-01,
       -3.31055671e-01, -7.20935285e-01,  1.83179229e-01, -5.77666402e-01,
        1.08902186e-01,  8.91431719e-02, -3.00416678e-01, -5.19800782e-01,
        2.26132005e-01, -4.53856707e-01,  1.34320807e+00, -1.75419971e-01,
        8.11154302e-03,  3.18785191e-01,  8.93783808e-01,  7.38045335e-01,
        6.11145794e-01, -9.81240571e-01,  1.73126608e-01, -1.10258007e+00,
       -3.63942206e-01,  1.29719228e-01,  3.16669703e-01,  3.43850330e-02,
        7.46868476e-02,  1.29787803e-01, -3.03472996e-01,  1.00428402e+00,
       -6.75332174e-02, -3.96942377e-01,  8.94670427e-01, -2.52886713e-01,
        5.74499726e-01,  1.62248611e+00, -7.70755410e-01,  7.95776099e-02,
       -1.10789287e+00,  7.99653530e-02, -3.45991284e-01, -4.40355480e-01,
       -3.12472701e-01, -2.64104068e-01,  3.85500908e-01,  4.43865955e-01,
        1.27837324e+00,  1.88341960e-01, -1.25464173e-02, -4.52126786e-02,
       -4.42109257e-01, -1.01564622e+00,  1.15631902e+00,  1.73520297e-01,
       -7.25366995e-02,  1.53365314e-01,  3.29049945e-01,  5.04136503e-01,
       -2.14477062e-01, -4.66821969e-01,  1.21593297e+00, -6.23564482e-01,
       -1.76049635e-01,  3.68009210e-01,  1.43365538e+00, -2.10555419e-01,
        1.87170684e-01,  2.48393282e-01, -5.39780140e-01,  3.21443111e-01,
        2.41344541e-01, -2.97151301e-02, -1.90358937e-01, -4.66457307e-01,
        1.01792169e+00, -5.40964007e-01, -1.71663955e-01, -5.61756492e-01,
        2.39092410e-01, -9.26651716e-01, -2.38419905e-01, -2.77890861e-01,
        3.19311947e-01,  9.35099244e-01, -2.58595973e-01, -1.06342542e+00,
        4.31788772e-01,  1.79190412e-01,  3.65138389e-02,  3.97818685e-01,
        1.10016875e-01,  1.34564251e-01,  4.34439868e-01,  3.43921125e-01,
        2.80233342e-02, -7.24319577e-01,  4.74351384e-02,  2.87648857e-01,
       -8.53145272e-02,  1.82817534e-01, -4.49824035e-02, -3.74673158e-01,
       -9.11714494e-01, -1.50417888e+00,  3.30964565e-01,  2.53778696e-02,
        1.23715393e-01, -1.56936254e-02, -3.22743714e-01,  6.69899881e-01,
        6.16494358e-01, -4.25103247e-01,  3.07429403e-01, -1.26492560e-01,
       -6.80155307e-02,  3.19851309e-01,  8.86460483e-01,  3.65109861e-01,
        1.98246688e-01, -3.20950985e-01,  1.79589048e-01, -1.47836775e-01,
        6.56161904e-01,  3.08207989e-01,  5.33696339e-02,  2.72250891e-01,
        6.99501574e-01, -2.79099464e-01, -1.95674747e-01,  1.38472319e-01,
        6.65660143e-01,  1.19522974e-01,  3.85020226e-01,  8.24869722e-02,
       -5.23718238e-01,  4.17465210e-01,  7.73328900e-01,  1.00482762e+00,
        8.88383836e-02,  4.41238508e-02, -9.08535868e-02, -4.16008420e-02,
        9.32479948e-02,  4.35473233e-01,  4.70238507e-01, -2.92048305e-01,
        1.39180571e-03, -5.47004975e-02,  3.95897150e-01, -3.96934956e-01,
       -6.96464539e-01, -1.71686932e-01,  2.82353044e-01, -5.29325724e-01,
       -3.61217767e-01, -6.40822411e-01,  3.54514599e-01, -1.33354619e-01,
        1.30633786e-01, -1.51060164e-01, -3.09159636e-01,  3.33260864e-01,
        4.74506289e-01,  5.82732558e-01,  7.66285956e-01,  5.12709141e-01,
       -7.51973808e-01, -3.88545007e-01, -1.65736437e-01, -2.95805521e-02,
       -9.82876301e-01, -2.39754990e-02, -3.04969817e-01, -3.86533111e-01,
       -8.59300315e-01,  2.70871371e-01, -4.79292125e-01, -5.22040963e-01,
       -5.62489510e-01, -6.21126771e-01,  2.27671504e-01, -6.75457060e-01,
        4.84668463e-03, -4.26808029e-01, -7.43594646e-01, -4.78056192e-01,
        3.28706324e-01, -2.21616194e-01,  4.61226046e-01,  3.89836371e-01,
        1.02956796e+00,  1.44849956e-01, -4.16387230e-01,  3.17932189e-01,
        6.09215796e-01,  8.50788578e-02,  1.69859976e-02, -1.90923922e-03,
       -1.41532108e-01,  7.61594832e-01,  1.14959903e-01, -1.50777726e-02,
        9.77984190e-01, -3.30327511e-01, -3.54442656e-01, -6.93326443e-02,
       -2.10872129e-01,  4.75837231e-01,  2.89487720e-01, -1.34425864e-01,
        4.03877020e-01, -7.92971611e-01, -5.61518252e-01, -8.57048184e-02,
       -5.12900591e-01,  4.28324968e-01,  9.16987062e-01, -2.92831331e-01,
       -8.70310128e-01, -3.18630397e-01,  2.93486744e-01, -4.91765141e-01,
        1.10164329e-01, -3.48235369e-01,  8.33552957e-01,  4.46121693e-01,
       -3.39770675e-01, -6.91755116e-02, -2.17988133e-01, -2.92530060e-01,
       -9.53638703e-02, -2.73846954e-01, -4.53835666e-01, -5.51907063e-01,
        1.37018406e+00, -1.07466888e+00, -2.40810797e-01, -2.90590078e-01,
       -6.04365349e-01,  4.38216835e-01,  1.53014407e-01, -2.05716640e-01,
       -2.13501193e-02, -2.39116058e-01, -1.25600028e+00,  5.72408915e-01,
        9.44143981e-02, -4.09750074e-01, -4.26849157e-01,  4.22386110e-01,
       -1.07307890e-02,  7.65534163e-01, -7.28062689e-01,  3.42728555e-01,
        7.09327519e-01, -3.36992443e-01, -1.30274937e-01,  8.63672674e-01,
       -7.38347650e-01,  6.38158619e-01,  5.77082038e-01,  4.51370835e-01,
        3.94511633e-02,  7.59295821e-02,  1.80505767e-01,  5.32188416e-01,
       -3.12898189e-01, -3.08675855e-01, -1.01336861e+00,  6.20490253e-01,
       -3.94798875e-01, -2.97920387e-02,  2.38968328e-01, -2.12428346e-01,
        3.02318186e-01,  5.64925782e-02, -7.92200506e-01,  2.65981197e-01,
        2.97248334e-01,  1.08240807e+00, -2.35168651e-01,  1.53905541e-01,
        1.65141910e-01,  2.70040423e-01,  3.55357409e-01,  1.89189222e-02,
        3.66977513e-01, -4.48590547e-01,  8.95235300e-01, -3.87621820e-01,
       -3.05993140e-01,  3.95487733e-02, -2.99613982e-01, -2.79768109e-01,
        1.08422613e+00,  4.59395409e-01, -4.51717377e-01, -6.57984138e-01,
       -2.70522177e-01, -1.05436802e-01,  7.23901451e-01, -6.91674650e-02,
       -3.93603325e-01,  5.39537780e-02,  1.67098224e-01, -6.60045743e-02,
        2.76782870e-01,  2.39553079e-01,  2.09176898e-01,  7.74876103e-02,
       -7.19175577e-01,  2.39315450e-01, -8.33574712e-01, -5.78395665e-01,
        1.27080321e+00, -6.51922047e-01,  1.69429228e-01, -8.62320215e-02,
        9.01879728e-01, -1.02395803e-01, -1.85540020e-01,  9.00965452e-01,
        1.50749967e-01,  2.39200532e-01, -6.80322349e-01,  5.23667812e-01,
        5.40026873e-02,  8.21911633e-01, -7.14460433e-01, -9.28200781e-02,
        5.31517267e-01,  3.30828130e-04, -9.91746783e-03, -1.06497717e+00,
       -3.04324448e-01, -9.22092199e-02, -1.36606380e-01,  2.09262401e-01,
       -2.05144674e-01, -8.41885954e-02, -3.08458805e-01, -6.73586130e-01,
       -2.83161789e-01,  8.24611112e-02,  3.00529636e-02, -1.52866542e-01,
        3.56531411e-01, -1.13141388e-01, -1.11320108e-01, -8.71826172e-01,
       -4.19966191e-01,  1.21276677e-01, -1.21094495e-01, -2.41324574e-01,
        6.08003676e-01,  5.08618176e-01,  3.48658085e-01,  1.31567437e-02,
       -5.48984468e-01,  4.13789749e-01,  3.10284793e-01, -4.80650961e-01,
        8.28027904e-01,  1.57253861e-01,  6.92840874e-01,  3.18598866e-01,
       -2.94869505e-02, -3.12915772e-01, -1.11278462e+00, -3.46153900e-02,
       -7.64964461e-01, -1.84420452e-01, -9.90631208e-02, -1.37763345e+00,
       -2.17429101e-01, -2.25025229e-03,  2.71595716e-01,  3.43628794e-01],
      dtype=float32)

In [56]:
#Compute similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity_bert = cosine_similarity(sentence_embeddings)

In [57]:
similarity_bert

array([[1.0000002 , 0.73503464, 0.5243318 , ..., 0.4893261 , 0.42444232,
        0.5738556 ],
       [0.73503464, 1.        , 0.6462196 , ..., 0.67438996, 0.6294035 ,
        0.61967415],
       [0.5243318 , 0.6462196 , 1.        , ..., 0.7582776 , 0.6811994 ,
        0.5672052 ],
       ...,
       [0.4893261 , 0.67438996, 0.7582776 , ..., 1.0000001 , 0.7448809 ,
        0.5912813 ],
       [0.42444232, 0.6294035 , 0.6811994 , ..., 0.7448809 , 1.0000001 ,
        0.6019321 ],
       [0.5738556 , 0.61967415, 0.5672052 , ..., 0.5912813 , 0.6019321 ,
        0.9999999 ]], dtype=float32)

In [120]:
def recommend(movie):
    index = dataframe[dataframe['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity_bert[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:9]:
        print(dataframe.iloc[i[0]].title)
        print(dataframe.iloc[i[0]].	movie_id)

In [121]:
recommend('Batman Begins')

The Dark Knight
155
The Dark Knight Rises
49026
Batman v Superman: Dawn of Justice
209112
Batman
268
Batman
2661
Batman Forever
414
Batman: The Dark Knight Returns, Part 2
142061
Teenage Mutant Ninja Turtles
98566

In [122]:
recommend('Harry Potter and the Philosopher\'s Stone')

Harry Potter and the Goblet of Fire
674
Harry Potter and the Half-Blood Prince
767
A Simple Wish
17834
Stitches
115210
Elf
10719
Just Visiting
56715
The Muppets
64328
The NeverEnding Story
34584

In [127]:
recommend(Toy Story)

SyntaxError: invalid syntax (Temp/ipykernel_9368/863080873.py, line 1)

In [72]:
import pickle

In [74]:
pickle.dump(dataframe,open('movies_data.pkl','wb'))
pickle.dump(similarity_bert,open('similarityBert.pkl','wb'))
pickle.dump(sentence_embeddings,open('text_vectors.pkl','wb'))

# cf (matrix factorization)

In [240]:
from surprise import SVD
from surprise import BaselineOnly
from surprise import Dataset
from surprise import Reader
from surprise import accuracy
from surprise import NormalPredictor
from surprise.model_selection import train_test_split
from surprise.model_selection import cross_validate
from surprise.model_selection import KFold
from surprise.model_selection import PredefinedKFold
from surprise.model_selection import GridSearchCV

ModuleNotFoundError: No module named 'surprise'

In [ ]:
reader = Reader(rating_scale=(0.5, 5)) #line_format by default order of the fields
data = Dataset.load_from_df(data_cf[["userid", "title", "rating"]] , reader=reader)

trainset = data.build_full_trainset()

testset = trainset.build_anti_testset()

Number of Factors and RMSE

In [ ]:
def rmse_vs_factors(algorithm, data):
  """Returns: rmse_algorithm i.e. a list of mean RMSE of CV = 5 in cross_validate() for each  factor k in range(1, 101, 1)
  100 values 
  Arg:  i.) algorithm = Matrix factoization algorithm, e.g SVD/NMF/PMF, ii.)  data = surprise.dataset.DatasetAutoFolds
  """
  
  rmse_algorithm = []
  
  for k in range(1, 101, 1):
    algo = algorithm(n_factors = k)
    
    #["test_rmse"] is a numpy array with min accuracy value for each testset
    loss_fce = cross_validate(algo, data, measures=['RMSE'], cv=5, verbose=False)["test_rmse"].mean() 
    rmse_algorithm.append(loss_fce)
  
  return rmse_algorithm

In [ ]:
rmse_svd = rmse_vs_factors(SVD,data)

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
def plot_rmse(rmse, algorithm):
  """Returns: sub plots (2x1) of rmse against number of factors. 
     Vertical line in the second subplot identifies the arg for minimum RMSE
    
     Arg: i.) rmse = list of mean RMSE returned by rmse_vs_factors(), ii.) algorithm = STRING! of algo 
  """
  
  plt.figure(num=None, figsize=(11, 5), dpi=80, facecolor='w', edgecolor='k')

  plt.subplot(2,1,1)
  plt.plot(rmse)
  plt.xlim(0,100)
  plt.title("{0} Performance: RMSE Against Number of Factors".format(algorithm), size = 20 )
  plt.ylabel("Mean RMSE (cv=5)")

  plt.subplot(2,1,2)
  plt.plot(rmse)
  plt.xlim(0,50)
  plt.xticks(np.arange(0, 52, step=2))

  plt.xlabel("{0}(n_factor = k)".format(algorithm))
  plt.ylabel("Mean RMSE (cv=5)")
  plt.axvline(np.argmin(rmse), color = "r")

In [ ]:
plot_rmse(rmse_svd,"SVD")

GridsearchCV (Sample)

In [ ]:
param_grid = {'n_factors': [9,10,12,15,17,21,25,38]}
gs = GridSearchCV(SVD, param_grid, measures=['rmse'], cv=5)
gs.fit(data)


# best RMSE score
print(gs.best_score['rmse'])

# combination of parameters that gave the best RMSE score
print(gs.best_params['rmse'])

In [ ]:
algo_SVD = SVD(n_factors = 25)
algo_SVD.fit(trainset)


# Predict ratings for all pairs (i,j) that are NOT in the training set.
testset = trainset.build_anti_testset()

predictions = algo_SVD.test(testset)

# subset of the list  predictions
predictions[0:2]

In [ ]:
predictions